---
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: pch-d
 spec:
   replicas: 2
   template:
     metadata:
       labels:
         app: web
     spec:
       containers:
         - name: rss-reader
           image: varunjoshi29/friendlyhello:latest
           ports:
             - containerPort: 88
