---
apiVersion: v1
kind: Pod
metadata:
  name: pch-p
  labels:
    app: web
spec:
  containers:
    - name: rss-reader
      image: varunjoshi29/friendlyhello:latest
      ports:
        - containerPort: 88
